package it.polimi.se2018.view.cli;

public enum CLIState
{
    MENU_CLIENT_SERVER,
    MENU_ASKING_PLAYER_NICKNAME,
    GAME_STARTED,
    GAME_ASK_PLAYER_FOR_ACTION,
    GAME_ASK_PLAYER_FOR_ACTION_CARDS,
    GAME_ASK_PLAYER_FOR_DRAFTING,
    GAME_ASK_PLAYER_FOR_ADDING_DICE
}
