package it.polimi.se2018.view.cli;

public enum CLIState
{
    MENU_CLIENT_SERVER,
    MENU_NEW_PLAYER_ASKING_NICKNAME,
    MENU_CLIENT_ASKING_IP,
    MENU_CLIENT_ASKING_PORT,
    MENU_CLIENT_ASKING_NICKNAME,
    GAME_STARTED,
    GAME_ASK_PLAYER_FOR_ACTION,
    GAME_ASK_PLAYER_FOR_ACTION_CARDS,
    GAME_ASK_PLAYER_FOR_DRAFTING,
    GAME_ASK_PLAYER_FOR_ADDING_DICE
}
