package it.polimi.se2018.model.publicobjectivecards;

import it.polimi.se2018.model.Board;
import it.polimi.se2018.model.Card;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 * Abstract class used to represent a public objective card.
 * @author Matteo Gagliano
 * @author Carmelo Fascella
 * @author Generoso Imparato
 */
public abstract class PublicObjectiveCard extends Card
{
    protected int                 points;
    private static final int      NUMBER_OF_CARDS = 10;

    /**
     * Constructor that creates a PublicObjectiveCard assigning a name, a description and points
     * @param name name of the Card
     * @param description describes how to use the Card
     * @param points points that contribute to the score of every Player
     */
    public PublicObjectiveCard (String name, String description, int points)
    {
        super(name, description);
        this.points = points;
    }

    /**
     * Copy constructor
     * @param card source instance to be cloned
     */
    public PublicObjectiveCard(PublicObjectiveCard card)
    {
        super(card);
        this.points = card.points;
    }


    /**
     * Generates a number of different random public objective cards
     * @param numOfCards number of public objective cards generated by the method
     * @return an ArrayList of PublicObjectiveCards randomly generated
     */
    public static List<PublicObjectiveCard> getRandomCards(int numOfCards)
    {
        List<PublicObjectiveCard> ret = new ArrayList<>();
        List<Integer>  randomList = new ArrayList<>();

        for(int i=0; i<numOfCards; i++)
        {
            int rand;
            do                                                          //makes sure that the random number generated
            {                                                           //is different from the others in order to have different cards
                rand = new Random().nextInt(NUMBER_OF_CARDS);
                if(!randomList.contains(rand))                          //adds the random number only if it's not been already generated
                    randomList.add(rand);
            }
            while(randomList.size() < i+1);                              //makes sure that a different random number is added


            switch(rand)                                                //generates a random PublicObjectiveCard
            {
                case 0: ret.add(new ColorDiagonalsCard()); break;
                case 1: ret.add(new ColorVarietyCard()); break;
                case 2: ret.add(new ColumnColorVarietyCard()); break;
                case 3: ret.add(new ColumnShadeVarietyCard()); break;
                case 4: ret.add(new DeepShadesCard()); break;
                case 5: ret.add(new LightShadesCard()); break;
                case 6: ret.add(new MediumShadesCard()); break;
                case 7: ret.add(new RowColorVarietyCard()); break;
                case 8: ret.add(new RowShadeVarietyCard()); break;
                case 9: ret.add(new ShadeVarietyCard()); break;
                default: break;
            }
        }

        return ret;
    }

    /**
     * It's used to calculate the score due to the PublicObjectiveCard in a given Board
     * @param board Board where to calculate the score associated to the PublicObjectiveCard
     * @return an int representing the score associated to the Board passed by parameter
     */
    public abstract int score (Board board);
}
